---

    name: Weekly build and deploy Ansible devel package docs
    on:
      schedule:
        # Run at 05:17 on Mondays
        - cron: '17 5 * * 1'

    jobs:
      build-package-docs:
        uses: ./.github/workflows/reusable-build-docs.yaml
        with:
          repository-owner: ansible
          repository-name:  ansible-documentation
          repository-branch: devel
          ansible-package-version: devel
        secrets:
          DOCS_BOT_TOKEN: ${{ secrets.DOCS_BOT_TOKEN }}
    
      deploy-package-docs:
        needs: build-package-docs
        uses: ./.github/workflows/reusable-deploy-docs.yaml
        with:
          ansible-package-version: devel
          deployment-environment: production
          repository-owner: ansible
          repository-branch:  devel
        secrets:
          DEPLOY_DOC_BUILD: ${{ secrets.DEPLOY_DOC_BUILD }}
    